apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "slice-prb-prediction-rapp.name" . }}-configmap
  labels:
    {{- include "slice-prb-prediction-rapp.labels" . | nindent 4 }}
data:
{{ tpl (.Files.Glob "resources/config/config.json").AsConfig . | indent 2 }}